### ISSUE TITLE
Crashes while editing a track on Android 13

### ISSUE THREAD

**Issue by Ao1Pointblank** [lordi/tickmate#162]
Editing color or icon fields causes the app to crash (though it does not actually close the app completely)

**Comment by grrrrr** [comment]
Tickmate v1.4.13 from F-Droid:

Changing icon did not work for me,  it does not cause a crash error but just dumps me back to the task screen pre edit being selected.

steps
1. open tickmate
2. select one of the tasks
3. click the pencil to edit task
4. click the task icon 
5. app drops back to step 2-3

Changing color does however cause a crash notification,   

steps
1. open tickmate
2. select one of the tasks
3. click the pencil to edit task
4. click the color 
5. app crashes (but does not close)


error is as follows


```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101800:user/release-keys
package: de.smasi.tickmate:48
process: de.smasi.tickmate

java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.WindowInsetsController.show(int)' on a null object reference
	at android.preference.EditTextPreference.showDialog(EditTextPreference.java:142)
	at android.preference.DialogPreference.onClick(DialogPreference.java:300)
	at android.preference.Preference.performClick(Preference.java:1163)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3210)
	at android.widget.AbsListView$3.run(AbsListView.java:4176)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by matjon** [comment]
Hello,
Thank you for writing this app, it is very helpful to me.

This also happens on Android 12L (LineageOS 19.1). Downgrading to 1.4.11 does not help.

Output from logcat:
```
12-03 18:37:40.686     0     0 I         : [NVT-ts][info] nvt_ts_work_func 1642: Number of fingers to process = 0 (698, 722)
12-03 18:37:40.797  9285  9285 D AndroidRuntime: Shutting down VM
12-03 18:37:40.799  9285  9285 E AndroidRuntime: FATAL EXCEPTION: main
12-03 18:37:40.799  9285  9285 E AndroidRuntime: Process: de.smasi.tickmate, PID: 9285
12-03 18:37:40.799  9285  9285 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.WindowInsetsController.show(int)' on a null object reference
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.preference.EditTextPreference.showDialog(EditTextPreference.java:142)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.preference.DialogPreference.onClick(DialogPreference.java:300)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1163)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:261)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3190)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4156)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-03 18:37:40.799  9285  9285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-03 18:37:40.806  1998  9284 W ActivityTaskManager:   Force finishing activity de.smasi.tickmate/.views.TrackPreferenceActivity
12-03 18:37:40.808  1998  9383 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-03 18:37:40.829  1998  2153 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-03 18:37:40.829  1998  2153 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-03 18:37:40.882  1998  2143 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 1000; state: ENABLED
12-03 18:37:40.934  2562  2575 W System  : A resource failed to call release. 
12-03 18:37:40.934  2562  2575 W System  : A resource failed to call release. 
12-03 18:37:41.056  1998  2143 W Looper  : Slow dispatch took 125ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@7bf50b0 m=0
12-03 18:37:41.100     0     0 I FG      : fg_somc_get_real_temp: batt:285 aux:-2730 -> real battery temp:285
12-03 18:37:41.100     0     0 I FG      : fg_somc_jeita_step_charge_work: [Charging] RTEMP:285 IBATT:-161mA VBATT:3851mV VCELL:3847mV VCELL_MAX:3857
12-03 18:37:41.100     0     0 I PMI     : smblib_somc_handle_jeita_step_fv: set fv:4380000
12-03 18:37:41.105  2764  5150 I DPMJ    : |REQ:RCVR| DPM creating socket
12-03 18:37:41.322  1998  2145 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{e4aad90 u0 de.smasi.tickmate/.views.TrackPreferenceActivity t12600 f}}
12-03 18:37:41.325  1998  2145 W ActivityTaskManager: Activity pause timeout for ActivityRecord{e4aad90 u0 de.smasi.tickmate/.views.TrackPreferenceActivity t12600 f}}
```

**Comment by Kochanac** [comment]
+1

**Comment by fabmazz** [comment]
Trying to change the icon also makes the app crash for me. Android 13, Galaxy A52s
```
01-15 17:35:00.666 32200 32200 I DecorView: setWindowBackground: isPopOver=false color=0 d=android.graphics.drawable.ColorDrawable@4f3ecf7
01-15 17:35:00.668 32200 32200 D ScrollView: initGoToTop
01-15 17:35:00.670 32200 32200 W Settings: Setting show_button_background has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
01-15 17:35:00.674 32200 32225 D NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
01-15 17:35:00.689 32200 32200 D InsetsController: onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 1080, 2400), mDisplayCutout=DisplayCutout{insets=Rect(0, 88 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(512, 0 - 568, 88), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=1080 displayHeight=2400 physicalDisplayWidth=1080 physicalDisplayHeight=2400 density={2.8125} cutoutSpec={M 0,0 M 0,11.43427858034597 a 9.899054752987353,9.899054752987353 0 1,0 0,19.79810950597471 a 9.899054752987353,9.899054752987353 0 1,0 0,-19.79810950597471 Z @dp} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=90, center=Point(90, 90)}, RoundedCorner{position=TopRight, radius=90, center=Point(990, 90)}, RoundedCorner{position=BottomRight, radius=90, center=Point(990, 2310)}, RoundedCorner{position=BottomLeft, radius=90, center=Point(90, 2310)}]}  mRoundedCornerFrame=Rect(0, 0 - 1080, 2400), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(956, 0 - 1080, 88) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][1080,88], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][0,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[1080,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][1080,122], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][1080,88], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][1080,88], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,2265][1080,2400], mVisible=true, mInsetsRoundedCornerFrame=false} } host=de.smasi.tickmate/de.smasi.tickmate.views.TrackPreferenceActivity from=android.view.ViewRootImpl.setView:1700
01-15 17:35:00.696 32200 32200 I ViewRootImpl@ac685d0[TrackPreferenceActivity]: setView = com.android.internal.policy.DecorView@4153991 TM=true
01-15 17:35:00.697 32200 32200 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-15 17:35:00.698 32200 32200 E AndroidRuntime: FATAL EXCEPTION: main
01-15 17:35:00.698 32200 32200 E AndroidRuntime: Process: de.smasi.tickmate, PID: 32200
01-15 17:35:00.698 32200 32200 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.WindowInsetsController.show(int)' on a null object reference
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.preference.EditTextPreference.showDialog(EditTextPreference.java:147)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.preference.DialogPreference.onClick(DialogPreference.java:303)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1310)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:276)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3558)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4711)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8741)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
01-15 17:35:00.698 32200 32200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
01-15 17:35:00.734 32200 32200 I Process : Sending signal. PID: 32200 SIG: 9
```
