### ISSUE TITLE
Cannot start tickmate

### ISSUE THREAD

**Issue by CrateDepth** [lordi/tickmate#164]
Whenever I try to start tickmate, it crashes.  I go the following exception log report on it...

> 12-03 21:45:26.705 24686 24686 D tickmate: Opening database
12-03 21:45:26.732 24686 24686 E AndroidRuntime: Process: de.smasi.tickmate, PID: 24686
12-03 21:45:26.732 24686 24686 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.smasi.tickmate/de.smasi.tickmate.Tickmate}: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.views.TickHeader.getCurrentGroupId(TickHeader.java:152)
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.views.TickHeader.getTracksForCurrentGroup(TickHeader.java:147)
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.views.TickHeader.initializeTrackHeader(TickHeader.java:132)
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.views.TickHeader.refresh(TickHeader.java:83)
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.views.TickHeader.initialize(TickHeader.java:73)
12-03 21:45:26.732 24686 24686 E AndroidRuntime: 	at de.smasi.tickmate.Tickmate.onCreate(Tickmate.java:79)
12-03 21:45:26.743   986  4899 W ActivityManager: crash : de.smasi.tickmate,10389
12-03 21:45:26.750   986  4899 W ActivityTaskManager:   Force finishing activity de.smasi.tickmate/.Tickmate

#141 may OR may not be related to the above.

**Comment by lordi** [comment]
Thanks for the report. Android Version might be relevant here?

Unfortunately I can not really devote much time to Tickmate currently. PRs are welcome.
